CREATE TABLE IF NOT EXISTS pages (
    slug VARCHAR(255) NOT NULL PRIMARY KEY,
    content MEDIUMTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
