package app

// mainPageHTML returns a curated article for the EndlessWiki main page.
func mainPageHTML() string {
	return `
<h1>EndlessWiki</h1>
<div class="endlesswiki-body">
  <p><strong>EndlessWiki</strong> is a continuously generated encyclopedia. Inspired by <a href="/wiki/wikipedia">Wikipedia</a>, it allows users to collectively explore the knowledge inside a large language model.</p>

  <h2>How it works</h2>
  <p>When a user clicks a link in an existing article:</p>
  <ol>
    <li>Normalise the slug and check the archive for an existing article.</li>
    <li>If the page is missing, call Groq's <code>moonshotai/kimi-k2-instruct-0905</code> model to draft clean HTML.</li>
    <li>Persist the result so future users receive the cached version instantly.</li>
  </ol>

  <h2>Why links matter</h2>
  <p>New pages can only be discovered by following existing links. Direct navigation to unknown slugs is blocked, so no cheating!</p>

  <p>The content in EndlessWiki is generated by a large language model, so trust it at your own risk.</p>

  <p>Built by <a href="https://www.seangoedecke.com">Sean Goedecke</a>. I hope you like it!</p>

</div>`
}
