package app

// mainPageHTML returns a curated article for the EndlessWiki main page.
func mainPageHTML() string {
    return `
<h1>EndlessWiki</h1>
<div class="endlesswiki-body">
  <p><strong>EndlessWiki</strong> is a continuously generated encyclopedia. Inspired by <a href="/wiki/wikipedia">Wikipedia</a>, it allows users to explore the graph of knowledge inside a large language model.</p>

  <p>When a user clicks a link, EndlessWiki calls the <code>moonshotai/kimi-k2-instruct-0905</code> model (via Groq) to draft a new article, which is then saved for all future visitors.</p>

  <p>The content in EndlessWiki is generated by a large language model, so trust it at your own risk.</p>

</div>`
}
