package app

// mainPageHTML returns a curated article for the EndlessWiki main page.
func mainPageHTML() string {
	return `
<h1>EndlessWiki</h1>
<div class="endlesswiki-body">
  <p><strong>EndlessWiki</strong> is a continuously generated encyclopedia. Inspired by <a href="/wiki/wikipedia">Wikipedia</a>, it allows users to collectively explore the knowledge inside a large language model.</p>

  <p>When a user clicks a link in an existing article, EndlessWiki first checks the archive for an existing article. If there isn't one, we call Groq's <code>openai/gpt-oss-120b</code> model to write the article on the fly. The article is then saved so other users receive the cached version instantly.</p>

  <p>New pages can only be discovered by following existing links. Direct navigation to unknown slugs is blocked, so no cheating.</p>

  <p>The content in EndlessWiki is generated by a large language model, so trust it at your own risk.</p>

  <p>Built by <a href="https://www.seangoedecke.com">Sean Goedecke</a>. I hope you like it!</p>

</div>`
}
